name: Linux Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  buildProcess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest
      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          sh setup.sh
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build Project.xml linux"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Linux
          path: 'export/release/linux/bin'