# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  WindowsBuild:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Dependancies!!!
        run: |
          haxelib install lime
          haxelib install openfl
          haxelib install hxdiscord_rpc
          haxelib install tjson
          haxelib git flixel-nova https://github.com/swordcube/flixel
          haxelib git flixel-addons-nova https://github.com/swordcube/flixel-addons
          haxelib git hscript-iris https://github.com/crowplexus/hscript-iris
          haxelib git yaml https://github.com/crowplexus/hx-yaml

      - name: Setup Lime and Flixel
        run: |
          haxelib run lime setup
          haxelib run flixel setup

      - name: Build
        run: haxelib run lime build windows
      - name: Publish Build
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Windows
          path: export/release/windows/bin
