name: Windows Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  buildProcess:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2.3.0
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
          setup.bat
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Windows
          path: export/release/windows/bin